---
version: '3.7'

networks:
  xes-platform-network:
    name: xes-platform-network

services:
  node-mail-sender:
    image: proxeus/node-mail-sender
    container_name: xes_node-mail-sender
    networks:
      - xes-platform-network
    restart: unless-stopped
    environment:
      PROXEUS_INSTANCE_URL: http://xes-platform:1323
      SERVICE_SECRET: "${PROXEUS_SERVICE_SECRET}"
      SERVICE_PORT: 8013
      REGISTER_RETRY_INTERVAL: 3
      SERVICE_URL: http://node-mail-sender:8013
      TZ: Europe/Zurich
      PROXEUS_SPARKPOST_API_KEY: "${PROXEUS_SPARKPOST_API_KEY}"
    ports:
      - "8013:8013"
